### ISSUE TITLE
Bump pre-commit GitHub Action from version 1.1.0 to version 2.0.0

### ISSUE THREAD

**Issue by ShahradR** [ShahradR/git-template#9]
A new release of the pre-commit GitHub Action has been released. This new version handles caching internally, eliminating the need to manage it using separate workflow tasks.

# Before, using `pre-commit/action@v1.1.0`
```yaml
pre-commit:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: set PY
      run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.1.0
```

# After, using `pre-commit/action@v2.0.0`
```yaml
pre-commit:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - uses: actions/setup-python@v1
  - uses: pre-commit/action@v2.0.0
```
